<li class="amscheckout-row" style="width:100%;">
    <div>
        <label for="billing:use_for_shipping_point" class="amscheckout-label amscheckout-label-radio"><?php echo $this->__('Fermo!Point Store Pickup') ?></label>
        <div class="amscheckout-control amscheckout-control-radio">
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_point" value="1"<?php if (Mage::helper('fpstorepickup')->getUseMethod()) : ?> checked="checked" <?php endif ?> onclick="$('shipping:same_as_billing').checked = true;$('shipping_area').hide();" class="radio" />
        </div>
    </div>
</li>
