<script type="text/javascript">
//<![CDATA[
    var fpStorePickup = new FermopointStorePickup(
        '<?php echo Mage::helper('fpstorepickup')->getChangeMethodUrl(); ?>',
        '<?php echo Mage::helper('fpstorepickup')->getSearchUrl(); ?>',
        '<?php echo Mage::helper('fpstorepickup')->getMediaUrl(); ?>',
        function (point) {
            var days = [];
            for (var i = 0; i < point.hours.length; i++) {
                days.push('<span class="dow">' + point.hours[i].day + '</span>' + point.hours[i].hours.join(', '));
            }
            return '<div class="fermopoint-info-window">' +
                '<div class="fermopoint-info-row title">' + point.name + '</div>' +
                '<div class="fermopoint-info-row select"><a class="fermopoint-select-me" rel="' + point.id + '" href="#">' + Translator.translate('Select this pick-up point') + '</a></div>' +
                '<div class="fermopoint-info-row"></div>' +
                '<div class="fermopoint-info-row address">' + point.street + ', ' + point.city + ', ' + point.postcode + ', ' + point.region + '</div>' +
                '<div class="fermopoint-info-row distance"><strong>' + Translator.translate('Distance') + ': </strong>' + point.distance + ' km </div>' +
                '<div class="fermopoint-info-row hours"><div class="hours-list">' + days.join('<br />') + '</div></div></div>';
        }
    );

    Event.observe('shipping:same_as_billing_point', 'click', function(event){
        fpStorePickup.setUseStorePickup(true);
        if ($('s_method_fpstorepickup_fpstorepickup'))
            $('s_method_fpstorepickup_fpstorepickup').checked = true;
        reviewInfo.update('shipping-address');
    });

    Event.observe('shipping:same_as_billing', 'click', function(event){
        fpStorePickup.setUseStorePickup(false);
        if ($('s_method_fpstorepickup_fpstorepickup'))
            $('s_method_fpstorepickup_fpstorepickup').checked = false;
        reviewInfo.update('shipping-address');
    });

    Event.observe('shipping:same_as_billing_no', 'click', function(event){
        fpStorePickup.setUseStorePickup(false);
        if ($('s_method_fpstorepickup_fpstorepickup'))
            $('s_method_fpstorepickup_fpstorepickup').checked = false;
        reviewInfo.update('shipping-address');
    });
//]]>
</script>
