<script type="text/javascript">
//<![CDATA[
    var fpStorePickup = new FermopointStorePickup(
        '<?php echo Mage::helper('fpstorepickup')->getChangeMethodUrl(); ?>',
        '<?php echo Mage::helper('fpstorepickup')->getSearchUrl(); ?>',
        '<?php echo Mage::helper('fpstorepickup')->getMediaUrl(); ?>',
        function (point) {
            var days = [];
            for (var i = 0; i < point.hours.length; i++) {
                days.push('<span class="dow">' + point.hours[i].day + '</span>' + point.hours[i].hours.join(', '));
            }
            return '<div class="fermopoint-info-window">' +
                '<div class="fermopoint-info-row title">' + point.name + '</div>' +
                '<div class="fermopoint-info-row select"><a class="fermopoint-select-me" rel="' + point.id + '" href="#">' + Translator.translate('Select this pick-up point') + '</a></div>' +
                '<div class="fermopoint-info-row"></div>' +
                '<div class="fermopoint-info-row address">' + point.street + ', ' + point.city + ', ' + point.postcode + ', ' + point.region + '</div>' +
                '<div class="fermopoint-info-row distance"><strong>' + Translator.translate('Distance') + ': </strong>' + point.distance + ' km </div>' +
                '<div class="fermopoint-info-row hours"><div class="hours-list">' + days.join('<br />') + '</div></div></div>';
        }
    );
    
    function initStorePickup() {
        var element = $('shipping:use_store_pickup'),
            control = $('shipping:different_shipping');
        if (element && control) {
            if (element.checked) {
                update_address_payment = 1;
                control.up('li').hide();
                control.checked = false;
            } else {
                control.up('li').show();
            }
        }
    }
    initStorePickup();
    
    function useStorePickup(element) {
        var control,
            old_update_address_payment;
        control = $('shipping:different_shipping');
        if (control) {
            if (element.checked) {
                control.up('li').hide();
                control.checked = false;
            } else {
                control.up('li').show();
            }
        }
        fpStorePickup.setUseStorePickup(element.checked, function (flag) {
            if (control) {
                old_update_address_payment = update_address_payment;
                update_address_payment = 1;
                showDifferentAdress();
                update_address_payment = old_update_address_payment;
            } else {
                save_address_information(save_address_url, true, true, true);
            }
        });
        
    }

//]]>
</script>
