<li class="control">
    <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_point" value="1"<?php if (Mage::helper('fpstorepickup')->getUseMethod()) : ?> checked="checked" <?php endif ?> onclick="$('shipping:same_as_billing').checked = true;" class="radio" />
    <label for="billing:use_for_shipping_point"><?php echo $this->__('Fermo!Point Store Pickup') ?></label>
</li>

